### ISSUE TITLE
Be aware of bug #26181

### ISSUE THREAD

**Issue by db0** [JCAguilera/better-drag-and-drop-sprite#2] opened 2020-12-18 22:08 UTC
Relying on mouse signals, will run into godotengine/godot#26181 if one tries to use multiple viewports

**Comment by JCAguilera** [comment] 2020-12-18 22:12
Thanks for letting me know 👌

**Comment by SirTobyB** [comment] 2023-07-12 22:19
Seems like this is finally fixed in https://github.com/godotengine/godot/pull/57894, which closes https://github.com/godotengine/godot/issues/17326 and this was an duplicate of the mentioned issue https://github.com/godotengine/godot/issues/26181.

**Closed as completed** 2023-09-15 13:59 UTC
